// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  bg: string;
  content: string;
  footer: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
